### ISSUE TITLE
when can we expect a simple CLI so we can natively just pack VPK files on linux 

### ISSUE THREAD

**Issue by Nbc66** [craftablescience/VPKEdit#41]
this is a highly requested feature as a lot of ppl would like to Pack vpk files directly on Linux as then we can automate steam builds without needing additional Windows servers everything could be done on one 1 server

**Comment by Nbc66** [comment]
the only thing i would like is to be able to just select the files list we create and just plop that into a multi chunk vpk

**Comment by Nbc66** [comment]
the vpk packer valve provides on linux is absolutly broken and not worth using at this point

**Comment by craftablescience** [comment]
> then we can automate steam builds without needing additional Windows servers
Honestly I didn't think of that, I'll get right on this

**Comment by Nbc66** [comment]
> > then we can automate steam builds without needing additional Windows servers
> 
> Honestly I didn't think of that, I'll get right on this

Thank you for this. Its going to be a life saver

**Comment by Nbc66** [comment]
just wanted to ask for a ETA on the CLI

**Comment by craftablescience** [comment]
Should be done with a basic implementation over the weekend, just reworking the base library a bit first
Progress is tracked in #42

**Comment by Nbc66** [comment]
> Should be done with a basic implementation over the weekend, just reworking the base library a bit first Progress is tracked in #42

That's amazing thank you again for this 

this is gonna help a lot of folks out

**Comment by craftablescience** [comment]
Closing, will upload a release as soon as the changelog is wrangled

**Comment by craftablescience** [comment]
https://github.com/craftablescience/VPKEdit/releases/tag/v4.0.0.1

Run with no arguments or `-h` / `--help` for more detailed information on how to use it. Right now it only supports packing, hopefully that's your only use case.

Also, I mention that this build is in beta since I made quite a few library changes, but it's been working fine for me so far. I'm in the process of setting up proper tests for the base library to find any bugs that might have snuck in, since I'm tired of testing it out by hand.

**Comment by Nbc66** [comment]
thank you so much this is great this will help a bunch ill make sure to report any bugs
