### ISSUE TITLE
Unable to overwrite existing files

### ISSUE THREAD

**Issue by Jarzka** [craftablescience/VPKEdit#57]
Hi

I'm trying to rename bots in Counter-Strike 2 by modifying their display names.

I used VPKEdit to open a file called `pak01_dir.vpk`. From there, I was able to locate the bot names in `resources/csgo_<language>.txt` files. However, modifying those files does not seem to work in any way:

- If I right click the "resource" folder and select "Add file" with the same name, the new file does not overwrite the old one
- If I remove a file from the resource folder, and then add my own modified file there, the old file has come back
- If I remove a file from the resource folder, save changes, close the program and open the same VPK file again, the removed file has come back

Am I doing something wrong?

**Comment by Jarzka** [comment]
I rebooted my whole machine and now the changes were saved. Not sure what caused the problem.

**Comment by Jarzka** [comment]
It seems that sometimes the modifications are saved and sometime not. Is this a bug?

**Comment by craftablescience** [comment]
Sounds like a bug to me, I'll look into it

**Comment by craftablescience** [comment]
This might be fixed in [the latest beta release](https://github.com/craftablescience/VPKEdit/releases/tag/v4.0.0.4) if you want to give it a shot - overwriting existing files now automatically removes the file if it's already present. I'm not sure why you were having problems with it when removing the file manually, I've never experienced that personally and I can't think of how it could happen

**Comment by craftablescience** [comment]
Closing, pretty sure this has been fixed. Please reopen if you continue to have this issue
